
config:
    send_anonymous_usage_stats: False
    use_colors: True

databricks_demo:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: matt_winkler_dev
      schema: dbt_mwinkler
      host: "{{ env_var('PROFILES_YML_HOST') }}"
      http_path: "{{ env_var('PROFILES_YML_HTTP_PATH') }}"
      token: "{{ env_var('PROFILES_YML_TOKEN') }}"