name: SQLFluff

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  lint-models:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.8]
    env: 
      DBT_PROFILES_DIR: ${{ github.workspace }}/.ci_cd
      PROFILES_YML_HOST: ${{ secrets.PROFILES_YML_HOST }}
      PROFILES_YML_HTTP_PATH: ${{ secrets.PROFILES_YML_HTTP_PATH }}
      PROFILES_YML_TOKEN: ${{ secrets.PROFILES_YML_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: SQLFluff lint models/ and apply fixes
        # https://github.com/yu-iskw/action-sqlfluff
        #uses: yu-iskw/action-sqlfluff@a28280f53bbb888a7a1c8d560c01b32b97269198
        uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          config: ${{ github.workspace }}/.github/workflows/additional_cfg.sqlfluff
          extra_requirements_txt: ${{ github.workspace }}/.github/workflows/extra_requirements.txt
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: ${{ github.workspace }}/dbt_transform_code/models
          reporter: github-pr-review
          sqlfluff_version: 1.4.5
          sqlfluff_command: fix # Or "lint"
          working-directory: ${{ github.workspace }}/dbt_transform_code
      - name: "Show outputs (Optional)" # Only works in "lint" mode
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'